language: c
dist: xenial
before_install:
  # Install ISE Eiffel
  - export TRAVIS_ISE_VERSION=18.07
  - export ISE_EIFFEL=$PWD/Eiffel_$TRAVIS_ISE_VERSION;
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export ISE_PLATFORM=linux-x86-64; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export ISE_PLATFORM=macosx-x86-64; fi
  - curl -sSL https://ftp.eiffel.com/pub/download/$TRAVIS_ISE_VERSION/Eiffel_${TRAVIS_ISE_VERSION}_gpl_101981-$ISE_PLATFORM.tar.bz2 | tar -x --bzip2
  - export PATH=$PATH:$ISE_EIFFEL/studio/spec/$ISE_PLATFORM/bin:$PATH:$ISE_EIFFEL/tools/spec/$ISE_PLATFORM/bin
  - echo `ec -version`

  # Install gobo
  - export MAKEFLAGS=-j2
  - export EPOSIX=$PWD
  - export GOBO=$PWD/gobo
  - export PATH=$PATH:$GOBO/bin
  - git clone --depth=1 https://github.com/gobo-eiffel/gobo.git
  - travis_wait 120 $GOBO/bin/install.sh -t gcc
  - gec --version
  - ls $GOBO/bin
  - cd $GOBO/tool/gepp/src; geant compile_ge; cp -p gepp $GOBO/bin/
  - cd $GOBO/tool/gelex/src; geant compile_ge; cp -p gelex $GOBO/bin/
  - cd $GOBO/tool/geyacc/src; geant compile_ge; cp -p geyacc $GOBO/bin/
  - ls $GOBO/bin
  - echo `gepp --version`

  - cd $EPOSIX
  - ./bootstrap

script:
  - ./configure --with-compiler=ge --prefix=$EPOSIX && make && make install
  - ec -batch -config eposix.ecf
