Return-Path: <cyrus@bmach.nederware.nl>
Received: from bmach.nederware.nl ([unix socket])
	by bmach.nederware.nl (Cyrus v2.1.9) with LMTP; Fri, 13 May 2005 03:05:07 +1200
X-Sieve: CMU Sieve 2.2
Return-Path: <SRS0=D52Q=TT=yahoo.com.tw=sendme_3g@bounce2.pobox.com>
Received: from localhost (localhost.nederware.nl [127.0.0.1])
	by bmach.nederware.nl (Postfix) with ESMTP id C783322E1E
	for <berend@localhost>; Fri, 13 May 2005 03:05:06 +1200 (NZST)
X-Original-To: berend@berenddeboer.net
Delivered-To: berend@berenddeboer.net
Received: from berenddeboer.net [207.44.218.14]
	by localhost with POP3 (fetchmail-6.2.5)
	for berend@localhost (single-drop); Fri, 13 May 2005 03:05:06 +1200 (NZST)
Received: from gold.pobox.com (gold.pobox.com [208.210.124.73])
	by plain.ev1servers.net (Postfix) with ESMTP id 3049145C1CC
	for <berend@berenddeboer.net>; Thu, 12 May 2005 10:04:34 -0500 (CDT)
Received: from gold.pobox.com (localhost [127.0.0.1])
	by gold.pobox.com (Postfix) with ESMTP id 434947290E
	for <berend@berenddeboer.net>; Thu, 12 May 2005 11:04:32 -0400 (EDT)
Delivered-To: berend@pobox.com
Received: from tigris.qatar.net.qa (tigris.qatar.net.qa [82.148.100.75])
	by gold.pobox.com (Postfix) with ESMTP id 6AB1A72C10
	for <berend@pobox.com>; Thu, 12 May 2005 11:04:24 -0400 (EDT)
Received: from chubbfireqatar.com.qa ([82.148.126.161])
 by tigris.qatar.net.qa (Sun Java System Messaging Server 6.1 HotFix 0.11
 (built Jan 28 2005)) with SMTP id <0IGE004UA6JKYO20@tigris.qatar.net.qa> for
 berend@pobox.com; Thu, 12 May 2005 16:38:10 -0300 (GMT)
Received: from 195.52.49.240 ([219.86.39.48]) by chubbfireqatar.com.qa with
 Microsoft SMTPSVC(6.0.3790.211); Thu, 12 May 2005 16:36:03 +0300
Date: Tue, 19 Jan 2038 11:14:07 +0800
From: =?Big5?B?uuu/77lxpGyz+A==?= <sendme_3g@yahoo.com.tw>
Subject:
 =?big5?B?v8um26ijw9Kye6itu6GqazzF/bF6vUequqzdqrqoo7PhISE+ICAgICAgIGJlcm==?=
 =?big5?B?bmljZWxpbm==?=
Sender: =?UNKNOWN?B?uuu/77lxpGyz+A==?= <sendme_3g@yahoo.com.tw>
To: berry521 <berry521@netvigator.com>
Reply-To: sendme_3g@yahoo.com.tw
Message-id: <CHUBB-SERVEROHFctXM00000746@chubbfireqatar.com.qa>
MIME-version: 1.0
X-MIMEOLE: Produced By Mircosoft MimeOLE V6.00.2600.0000
Content-type: text/html; charset=BIG-5
Content-transfer-encoding: 8BIT
X-Priority: 3
X-Library: Indy 9.00.10
X-OriginalArrivalTime: 12 May 2005 13:36:04.0000 (UTC)
 FILETIME=[8B113A00:01C556F7]

<!-- berry521@netvigator.com-->
<!-- 8aNOZ0-->
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
	<HEAD>
		<META CONTENT="text/html; charset=big5" HTTP-EQUIV="Content-Type">
		<META NAME="Generator" CONTENT="">
	    <style type="text/css">
<!--
.style6 {font-size: 12}
-->
        </style>
	<title>健康、美麗、終身享瘦</title></HEAD>
	<BODY TOPMARGIN="0" LEFTMARGIN="0" MARGINWIDTH="0" MARGINHEIGHT="0">
    <table width="608" border="1" align="center" bordercolor="#FFFFFF">
      <tr>
        <td><div align="center"><a href="http://%36%31%2e%36%36%2e%32%32%30%2e%32%33%30/%35%30%33%31%34%2d/%35%30%33%31%34%68%6d%2d%61%75%74%6f%6d%61%69%6c%2e%68%74%6d%6c"><font size="2" face="新細明體">看不到圖請連結</font></a></div></td>
      </tr>
      <tr>
        <td bordercolor="#CCCCCC"><div align="center">
          <TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0">
            <TR>
              <TD COLSPAN="3"><IMG SRC="http://%36%31%2e%36%36%2e%32%32%30%2e%32%33%30/%35%30%33%31%34%2d/%69%6d%61%67%65%73/%35%30%33%31%34_%31%2e%6a%70%67" WIDTH="600" BORDER="0" HEIGHT="135"></TD>
            </TR>
            <TR>
              <TD><IMG SRC="http://%36%31%2e%36%36%2e%32%32%30%2e%32%33%30/%35%30%33%31%34%2d/%69%6d%61%67%65%73/%35%30%33%31%34_%32%2e%6a%70%67" WIDTH="75" BORDER="0" HEIGHT="202"></TD>
              <TD WIDTH="472" HEIGHT="202" VALIGN="top" BACKGROUND="http://%36%31%2e%36%36%2e%32%32%30%2e%32%33%30/%35%30%33%31%34%2d/%69%6d%61%67%65%73/%35%30%33%31%34_%33%2e%6a%70%67"><FONT face="Times New Roman">
                <P DESIGNTIMESP="25458"><FONT face=新細明體>體重控制需體重與脂肪率兼顧，而減重期+維持期與服務人員配合，使細胞營養維持均衡以達減重而不復胖之效果。</FONT></P>
                <P><FONT face=新細明體>體重控制計劃已在59個國家，使用25年之草本營養食品，已有許多人減重、增重、保健成功之案例。</FONT></P>
                <P><FONT face=新細明體>本站不推銷產品，以體重控制客戶需要體重控制之環境，本工作夥伴以熱情做好售後服務。</FONT></P>
                <P><FONT face=新細明體>保障客戶權益，一切售後服務，在完善售後服務有詳細說明。</FONT></P>
              </FONT></TD>
              <TD><IMG SRC="http://%36%31%2e%36%36%2e%32%32%30%2e%32%33%30/%35%30%33%31%34%2d/%69%6d%61%67%65%73/%35%30%33%31%34_%34%2e%67%69%66" WIDTH="53" BORDER="0" HEIGHT="202"></TD>
            </TR>
            <TR>
              <TD COLSPAN="3"><IMG SRC="http://%36%31%2e%36%36%2e%32%32%30%2e%32%33%30/%35%30%33%31%34%2d/%69%6d%61%67%65%73/%35%30%33%31%34_%35%2e%6a%70%67" WIDTH="600" BORDER="0" HEIGHT="200"></TD>
            </TR>
            <TR>
              <TD COLSPAN="3"><IMG SRC="http://%36%31%2e%36%36%2e%32%32%30%2e%32%33%30/%35%30%33%31%34%2d/%69%6d%61%67%65%73/%35%30%33%31%34_%36%2e%6a%70%67" WIDTH="600" BORDER="0" HEIGHT="217"></TD>
            </TR>
          </TABLE>
        </div></td>
      </tr>
      <tr>
        <td bordercolor="#CCCCCC"><div align="center">
            <table width="600" border="0" align="center" cellpadding="0" cellspacing="0">
              <tr>
                <td valign="top"><form action="http://%77%77%77%2e%68%6f%67%6f%2e%63%6f%6d%2e%74%77/hongjing/cvboo.php" method="post" name="form1" onSubmit="YY_checkform('form1','Name','#q','0','姓 名','Tel','#q','0','電話','FromMail','#S','2','Mail信箱');return document.MM_returnValue">
                    <table align="center" class="box1">
                      <tr>
                        <td width="86" class="b style6">‧姓　　名：</td>
                        <td width="104"><input name="Name" type="text" class="b " id="Name" size="12">
                        </td>
                        <td width="59" class="b style6">‧性別：</td>
                        <td width="81"><span class="b style6">
                          <input name="Sex" type="radio" value="男" checked>
                    男
                    <input type="radio" name="Sex" value="女">
                    女</span></td>
                        <td width="84" class="b style6">‧出生日期：</td>
                        <td width="158"><input name="Byear" type="text" class="b " id="Byear" size="12">
                        </td>
                      </tr>
                      <tr>
                        <td class="b style6">‧連絡電話：</td>
                        <td><input name="Tel" type="text" class="b " id="Tel" size="12">
                        </td>
                        <td class="b style6">&nbsp;</td>
                        <td class="b style6">&nbsp;</td>
                        <td class="b style6">‧郵遞區號：</td>
                        <td><input name="Zip" type="text" class="b " id="Zip" size="12">
                        </td>
                      </tr>
                      <tr>
                        <td class="b style6">‧通訊地址：</td>
                        <td colspan="3"><input name="Address" type="text" class="b " id="Address" size="35">
                        </td>
                        <td class="b style6">‧婚　　姻：</td>
                        <td><span class="style6">
                          <input name="Marry" type="radio" value="未婚" checked>
                    未婚
                    <input type="radio" name="Marry" value="已婚 ">
                    已婚
                    <input type="radio" name="Marry" value="其它">
                    其它</span></td>
                      </tr>
                      <tr>
                        <td class="b style6">‧Mail信箱：</td>
                        <td colspan="3"><input name="FromMail" type="text" class="b " id="FromMail" size="35">
                        </td>
                        <td class="b style6">‧子女人數：</td>
                        <td><input name="Child" type="text" class="b " id="Child" size="12">
                        </td>
                      </tr>
                      <tr>
                        <td class="b style6">‧聯絡時間：</td>
                        <td colspan="2"><span class="style6">
                          <input name="Vtimes" type="radio" value="上午" checked>
                    上午
                    <input type="radio" name="Vtimes" value="下午">
                    下午
                    <input type="radio" name="Vtimes" value="晚上">
                    晚上</span></td>
                        <td class="b style6">&nbsp;</td>
                        <td class="b style6">&nbsp;</td>
                        <td>&nbsp;</td>
                      </tr>
                      <tr>
                        <td class="b style6">‧目前工作：</td>
                        <td colspan="5"><span class="style6">
                          <input type="radio" name="Work" value="在學">
                    在學
                    <input name="Work" type="radio" value="在職">
                    在職
                    <input name="Work" type="radio" value="待業" checked>
                    待業
                    <input type="radio" name="Work" value="其它">
                    其它</span></td>
                      </tr>
                      <tr>
                        <td height="57" class="b style6">‧備　　註： </td>
                        <td colspan="5"><textarea name="Memo" cols="65" rows="4" class="b style6" id="textarea">




【健康、美麗、終身享瘦】</textarea>
                        </td>
                      </tr>
                      <tr>
                        <td class="b"><input name="OrderSerial" type="hidden" id="OrderSerial" value="2004100417111339947713"></td>
                        <td colspan="5"><input type="submit" name="Submit" value="確認送出" style="height:20px;color:#000000;border:1px outset #FFFFFF;cursor:hand">
                            <input name="Email" type="hidden" value="automail168@yahoo.com.tw">
                        </td>
                      </tr>
                    </table>
                </form></td>
              </tr>
            </table>
        </div></td>
      </tr>
      <tr>
        <td bordercolor="#CCCCCC"><div align="center">
        </div></td>
      </tr>
    </table>
    <table width="510" border="0" align="center" cellpadding="0" cellspacing="0">
      <tr>
        <td scope="col"><div align="left">
            <p> <br>
            </p>
        </div></td>
      </tr>
      <tr>
        <td height="34"><div align="center">
            <form action="mailto:taiwan-mall@umail.hinet.net?subject=(終身瘦身)廣告取消" method="post" enctype="text/plain" name="nomail" id="nomail">
              <p>
                <input type="submit" name="Submit" value="取消廣告">
                <a href="http://counter.cgiworld.net/cgi-bin/redirect.cgi?id=edm50314" target=_top><img border=0 alt="HolyNet Free Counte r" src=http://counter.cgiworld.net/cgi-bin/counter.cgi?id=edm50314&l=b&d=b&r=255&g=30&b=0></a> </p>
            </form>
            <div align="center"></div>
        </div></td>
      </tr>
    </table>
    <p>&nbsp;</p>
    <p align="center">&nbsp;</p>
    <p>&nbsp;</p>
	</BODY>
</HTML>
<!-- berry521@netvigator.com-->
<!-- QM9EF0-->



