Return-Path: <cyrus@bmach.nederware.nl>
Received: from bmach.nederware.nl ([unix socket])
	by bmach.nederware.nl (Cyrus v2.1.9) with LMTP; Mon, 14 Apr 2003 20:35:07 +1200
X-Sieve: CMU Sieve 2.2
Return-Path: <master@89894.com>
Received: from localhost (localhost.nederware.nl [127.0.0.1])
	by bmach.nederware.nl (Postfix) with ESMTP id 1A17C22FD9
	for <berend@localhost>; Mon, 14 Apr 2003 20:35:06 +1200 (NZST)
Received: from berenddeboer.net [216.127.80.16]
	by localhost with POP3 (fetchmail-5.9.11)
	for berend@localhost (single-drop); Mon, 14 Apr 2003 20:35:06 +1200 (NZST)
Received: from rackshack.wellner.org (root@localhost)
	by berenddeboer.net (8.11.6/8.11.6) with ESMTP id h3E8XDB13780
	for <berend@berenddeboer.net>; Mon, 14 Apr 2003 08:33:19 GMT
X-ClientAddr: 207.106.49.22
Received: from dolly1.pobox.com (dolly1.pobox.com [207.106.49.22])
	by rackshack.wellner.org (8.11.6/8.11.6) with ESMTP id h3E8X7Z13764
	for <berend@berenddeboer.net>; Mon, 14 Apr 2003 08:33:13 GMT
Received: from dolly1.pobox.com (localhost.localdomain [127.0.0.1])
	by dolly1.pobox.com (Postfix) with ESMTP id 05A432BEF1
	for <berend@berenddeboer.net>; Mon, 14 Apr 2003 04:33:06 -0400 (EDT)
Delivered-To: berend@pobox.com
Received: from alias2.acm.org (alias2.acm.org [199.222.69.92])
	by dolly1.pobox.com (Postfix) with ESMTP id BC2AD2C081
	for <berend@pobox.com>; Mon, 14 Apr 2003 04:33:04 -0400 (EDT)
Received: from 89894.com ([211.221.139.200])
        by alias2.acm.org (ACM Email Forwarding Service) with SMTP id CRY73883
        for <berend@acm.org>; Mon, 14 Apr 2003 04:33:00 -0400
From: =?ks_c_5601-1987?B?vcUgIL/rICDDtg==?= <master@89894.com>
To: "berend@acm.org" <berend@acm.org>
Subject: *****SPAM***** =?ks_c_5601-1987?B?KLGksO0pwve+yMDHILTjueizv7v1LCDE+8T7x9Gzv7v1IL7GIH4hIMGkuLs/Pz9A?=
Date: Mon, 24 Feb 2003 06:02:30 +0900
MIME-Version: 1.0
Content-Type: text/html;
	charset="ks_c_5601-1987"
Content-Transfer-Encoding: 8bit
Message-Id: <20030414083304.BC2AD2C081@dolly1.pobox.com>
X-Spam-Status: Yes, hits=13.2 required=5.0
	tests=CLICK_BELOW,CTYPE_JUST_HTML,DATE_IN_PAST_96_XX,HTML_70_90,
	      KOREAN_UCE_SUBJECT,MAILTO_LINK,PLING_QUERY,
	      SPAM_PHRASE_08_13,SUBJ_FULL_OF_8BITS,TO_ADDRESS_EQ_REAL
	version=2.43
X-Spam-Flag: YES
X-Spam-Level: *************
X-Spam-Checker-Version: SpamAssassin 2.43 (1.115.2.20-2002-10-15-exp)
X-Spam-Report:   13.20 hits, 5 required;
  *  1.1 -- Subject: contains Korean unsolicited email tag
  *  0.2 -- To: repeats address as real name
  *  0.1 -- Subject has exclamation mark and question mark
  *  0.3 -- BODY: Asks you to click below
  *  1.4 -- BODY: Spam phrases score is 08 to 13 (medium)
            [score: 8]
  *  0.9 -- BODY: Message is 70-90% HTML tags
  *  0.2 -- BODY: Includes a URL link to send an email
  *  4.5 -- Subject is full of 8-bit characters
  *  1.5 -- Date: is 96 hours or more before Received: date
  *  3.0 -- HTML-only mail, with no text version


<HTML>
<HEAD>
<META NAME="GENERATOR" Content="Microsoft DHTML Editing Control">
<TITLE></TITLE>
</HEAD>
<BODY><FONT size=2><SPAN 
lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><FONT 
face="Times New Roman"><SPAN lang=EN-US 
style="mso-fareast-font-family: 굴림; mso-ascii-font-family: 굴림">&nbsp;</SPAN><SPAN 
lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'"><?xml:namespace 
prefix = o ns = "urn:schemas-microsoft-com:office:office" 
/><o:p></o:p></SPAN></FONT></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><SPAN lang=EN-US 
style="COLOR: red; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'"><STRONG><U>(광고)차안의 
담배냄새, 퀴퀴한냄새 아 ~! 정말???@<o:p></o:p></U></STRONG></SPAN></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><FONT 
face="Times New Roman"><SPAN lang=EN-US 
style="mso-fareast-font-family: 굴림; mso-ascii-font-family: 굴림">&nbsp;</SPAN><SPAN 
lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'"><o:p></o:p></SPAN></FONT></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><FONT 
face="Times New Roman"><SPAN lang=EN-US 
style="mso-fareast-font-family: 굴림; mso-ascii-font-family: 굴림">&nbsp;</SPAN><SPAN 
lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'"><o:p></o:p></SPAN></FONT></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><FONT 
face="Times New Roman"><SPAN lang=EN-US 
style="mso-fareast-font-family: 굴림; mso-ascii-font-family: 굴림">&nbsp;</SPAN><SPAN 
lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'"><o:p></o:p></SPAN></FONT></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN 
style="FONT-SIZE: 16pt; COLOR: red; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'; mso-bidi-font-size: 10.0pt">악취제거<SPAN 
lang=EN-US>. 곰팡이균 발생제거. 각종 </SPAN></SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN 
style="FONT-SIZE: 16pt; COLOR: red; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'; mso-bidi-font-size: 10.0pt"><SPAN 
lang=EN-US>세균 억제. 신선도 지속적 유지. 인체에는 </SPAN></SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN 
style="FONT-SIZE: 16pt; COLOR: red; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'; mso-bidi-font-size: 10.0pt"><SPAN 
lang=EN-US>전혀&nbsp;</SPAN></SPAN></B><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-SIZE: 16pt; COLOR: red; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'; mso-bidi-font-size: 10.0pt">무해한 
천연 항균 악취 제거제.<o:p></o:p></SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><FONT 
face="Times New Roman"><SPAN lang=EN-US 
style="mso-fareast-font-family: 굴림; mso-ascii-font-family: 굴림">&nbsp;</SPAN><SPAN 
lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'"><o:p></o:p></SPAN></FONT></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><FONT 
face="Times New Roman"><SPAN lang=EN-US 
style="mso-fareast-font-family: 굴림; mso-ascii-font-family: 굴림">&nbsp;</SPAN><SPAN 
lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'"><o:p></o:p></SPAN></FONT></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">1. 냉장고 냄새제거 및 
식품 신선도 지속 유지.....<o:p></o:p></SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><FONT 
face="Times New Roman"><B style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="mso-fareast-font-family: 굴림; mso-ascii-font-family: 굴림">&nbsp;</SPAN></B><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'"><o:p></o:p></SPAN></B></FONT></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">2. 옷장 속에 곰팡이 
냄새 제거 및 곰팡이 균 제거 &amp; 억제.....<o:p></o:p></SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><FONT 
face="Times New Roman"><B style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="mso-fareast-font-family: 굴림; mso-ascii-font-family: 굴림">&nbsp;</SPAN></B><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'"><o:p></o:p></SPAN></B></FONT></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">3. 주방 생선 튀김 
냄새. 된장 및 청국장 냄새 즉시 제거 및 </SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">&nbsp;&nbsp;&nbsp; 
각종 세균&nbsp;</SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">제거 &amp; 
억제.....<o:p></o:p></SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><FONT 
face="Times New Roman"><B style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="mso-fareast-font-family: 굴림; mso-ascii-font-family: 굴림">&nbsp;</SPAN></B><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'"><o:p></o:p></SPAN></B></FONT></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">4. 화장실 냄새 제거 및 
곰팡이 균 제거 &amp; 억제......<o:p></o:p></SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><FONT 
face="Times New Roman"><B style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="mso-fareast-font-family: 굴림; mso-ascii-font-family: 굴림">&nbsp;</SPAN></B><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'"><o:p></o:p></SPAN></B></FONT></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">5. 신발장 악취 제거 및 
발냄새 제거 무좀균. 제거 및 억제.......<o:p></o:p></SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><FONT 
face="Times New Roman"><B style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="mso-fareast-font-family: 굴림; mso-ascii-font-family: 굴림">&nbsp;</SPAN></B><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'"><o:p></o:p></SPAN></B></FONT></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">6. 실내 담배 냄새 및 
술 냄새 기타 음식 모든냄새.....<o:p></o:p></SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><FONT 
face="Times New Roman"><SPAN lang=EN-US 
style="mso-fareast-font-family: 굴림; mso-ascii-font-family: 굴림">&nbsp;</SPAN><SPAN 
lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'"><o:p></o:p></SPAN></FONT></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'"><SPAN 
style="mso-spacerun: yes">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN><B 
style="mso-bidi-font-weight: normal"><SPAN 
style="FONT-SIZE: 20pt; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'; mso-bidi-font-size: 10.0pt">홈 
페이지<SPAN lang=EN-US> : <A href="http://www.89894.com/"><SPAN 
style="FONT-FAMILY: 'Times New Roman'; mso-fareast-font-family: 바탕체">www.89894.com</SPAN></A><o:p></o:p></SPAN></SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><FONT 
face="Times New Roman"><SPAN lang=EN-US 
style="mso-fareast-font-family: 굴림; mso-ascii-font-family: 굴림">&nbsp;</SPAN><SPAN 
lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'"><o:p></o:p></SPAN></FONT></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">7. 실내 각종 악취제거 
및 땀냄새. 퀴퀴한 냄새 제거.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>곰팡이 균 
</SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">&nbsp;&nbsp;&nbsp; 
제거 및&nbsp;</SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">억제......<o:p></o:p></SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><FONT 
face="Times New Roman"><B style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="mso-fareast-font-family: 굴림; mso-ascii-font-family: 굴림">&nbsp;</SPAN></B><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'"><o:p></o:p></SPAN></B></FONT></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">8. 고층건물의 공조기 
닥트내의 악취제거 및 각종 곰팡이 균 </SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">&nbsp;&nbsp;&nbsp; 
제거 &amp;&nbsp;</SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN 
lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">억제.....<o:p></o:p></SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><FONT 
face="Times New Roman"><B style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="mso-fareast-font-family: 굴림; mso-ascii-font-family: 굴림">&nbsp;</SPAN></B><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'"><o:p></o:p></SPAN></B></FONT></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">9. 각종 동물의 분뇨 
냄새 및<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>악취제거 &amp; 냄새 
제거......</SPAN></B><SPAN lang=EN-US 
style="FONT-SIZE: 12pt; FONT-FAMILY: 바탕"><o:p></o:p></SPAN></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><SPAN 
lang=EN-US></SPAN>&nbsp;</P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">10. 승용차안의 
담배냄새와 퀴퀴한 냄새에는 꼭 필요한 </SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp; 
냄새 제거제...</SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><SPAN 
lang=EN-US></SPAN>&nbsp;</P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><FONT 
face="Times New Roman"><SPAN lang=EN-US 
style="mso-fareast-font-family: 굴림; mso-ascii-font-family: 굴림">&nbsp;</SPAN><SPAN 
lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'"><o:p></o:p></SPAN></FONT></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN 
style="FONT-SIZE: 14pt; COLOR: blue; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'; mso-bidi-font-size: 10.0pt">상호<SPAN 
lang=EN-US><SPAN style="mso-spacerun: yes">&nbsp; </SPAN>:<SPAN 
style="mso-spacerun: yes">&nbsp; </SPAN>쇼핑몰<o:p></o:p></SPAN></SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN 
style="FONT-SIZE: 14pt; COLOR: blue; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'; mso-bidi-font-size: 10.0pt">홈 
페이지<SPAN lang=EN-US> : <A href="http://www.89894.com/"><SPAN 
style="FONT-FAMILY: 'Times New Roman'; mso-fareast-font-family: 바탕체">www.89894.com</SPAN></A><o:p></o:p></SPAN></SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-SIZE: 14pt; COLOR: blue; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'; mso-bidi-font-size: 10.0pt">e-mail 
: <A href="mailto:master@89894.com"><SPAN 
style="FONT-FAMILY: 'Times New Roman'; mso-fareast-font-family: 바탕체">master@89894.com</SPAN></A><o:p></o:p></SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="FONT-SIZE: 14pt; COLOR: blue; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'; mso-bidi-font-size: 10.0pt"><SPAN 
style="mso-spacerun: yes">&nbsp;&nbsp; </SPAN>hp : 
011-281-1434<o:p></o:p></SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><FONT 
face="Times New Roman"><SPAN lang=EN-US 
style="mso-fareast-font-family: 굴림; mso-ascii-font-family: 굴림">&nbsp;</SPAN><SPAN 
lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'"><o:p></o:p></SPAN></FONT></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><FONT 
face="Times New Roman"><SPAN lang=EN-US 
style="mso-fareast-font-family: 굴림; mso-ascii-font-family: 굴림">&nbsp;</SPAN><SPAN 
lang=EN-US 
style="FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'"><o:p></o:p></SPAN></FONT></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN 
style="COLOR: blue; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">추사 
<SPAN lang=EN-US>: 와삭스는 식용으로 사용하는 와사비의 원료 식물 </SPAN></SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN 
style="COLOR: blue; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'"><SPAN 
lang=EN-US>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
고추냉이에서&nbsp;</SPAN></SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN 
lang=EN-US 
style="COLOR: blue; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">원료를 
추출하여 사용하므로 순수한 </SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="COLOR: blue; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;천연원료로서 
인체에는&nbsp;</SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="COLOR: blue; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">전혀<SPAN 
style="mso-spacerun: yes">&nbsp;</SPAN></SPAN></B><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="COLOR: blue; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">무해하며,&nbsp;</SPAN></B><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="COLOR: blue; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">각종 
</SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="COLOR: blue; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
부패성 및 세균성의 모든 악취를 제거 할뿐만 </SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="COLOR: blue; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;아니라 
각종 세균을</SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="COLOR: blue; mso-fareast-font-family: 굴림; mso-ascii-font-family: 굴림"><FONT 
face="Times New Roman">&nbsp;</FONT></SPAN></B><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="COLOR: blue; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'"><SPAN 
style="mso-spacerun: yes">&nbsp;</SPAN></SPAN></B><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="COLOR: blue; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">제거하는 
효과가 있으며 실내 </SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="COLOR: blue; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
공기를 청정</SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="COLOR: blue; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">하게 
유지시켜 기분을 상쾌하게&nbsp;</SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN 
style="COLOR: blue; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'">해준다<SPAN 
lang=EN-US>.</SPAN></SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><SPAN 
lang=EN-US></SPAN>&nbsp;</P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="COLOR: blue; mso-fareast-font-family: 굴림; mso-ascii-font-family: 굴림"><FONT 
face="Times New Roman">&nbsp;</FONT></SPAN></B><B 
style="mso-bidi-font-weight: normal"><SPAN lang=EN-US 
style="COLOR: blue; FONT-FAMILY: 굴림; mso-hansi-font-family: 'Times New Roman'"> 
감사 합니다....</SPAN></B></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><SPAN 
lang=EN-US></SPAN>&nbsp;</P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><SPAN 
lang=EN-US></SPAN>&nbsp;</P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left><SPAN lang=EN-US><FONT 
face="Times New Roman">&nbsp;<o:p></o:p></FONT></SPAN></P>
<P class=MsoNormal style="MARGIN: 0cm 0cm 0pt" align=left></SPAN></FONT>&nbsp;</P>
</td>
 </tr>
 <tr height=18 style='height:13.5pt'>
  <td height=18 class=xl24 style='height:13.5pt'>　</td>
  <td></td>
 </tr>
 <tr height=18 style='height:13.5pt'>
  <td height=18 class=xl25 style='height:13.5pt'>　</td>
  <td></td>
 </tr>
 <tr height=96 style='height:72.0pt'>
  <td height=96 class=xl27 width=320 style='height:72.0pt;width:240pt'>귀하의
  이메일주소는 인터넷서핑중알게되었으며, 메일주소이외의 어떠한 정보도 가지고 있지 않습니다. 메일수신을 원하지 않을경우 [수신거부]를
  눌러주십시요.. 감사 합니다. <font class=font8>If you feel that this information is not
  what you want, please click [HERE] requesting to be removed. Thank you, and
  we apologize for any inconvenience.</font></td>
  <td></td>
 </tr>
 <tr height=18 style='height:13.5pt'>
  <td height=18 class=xl24 style='height:13.5pt'>　</td>
  <td></td>
 </tr>
 <tr height=18 style='height:13.5pt'>
  <td height=18 class=xl25 style='height:13.5pt'>　</td>
  <td></td>
 </tr>
 <tr height=18 style='height:13.5pt'>
  <td height=18 colspan=2 style='height:13.5pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=252 style='mso-height-source:userset;height:189.0pt'>
  <td colspan=2 height=252 class=xl28 width=400 style='height:189.0pt;
  width:300pt'></BODY>
</HTML>





