Return-Path: <cyrus@bmach.nederware.nl>
Received: from bmach.nederware.nl ([unix socket])
	by bmach.nederware.nl (Cyrus v2.1.9) with LMTP; Sun, 20 Apr 2003 16:55:08 +1200
X-Sieve: CMU Sieve 2.2
Return-Path: <ariasparks@seznam.cz>
Received: from localhost (localhost.nederware.nl [127.0.0.1])
	by bmach.nederware.nl (Postfix) with ESMTP id 1054C22FDC
	for <berend@localhost>; Sun, 20 Apr 2003 16:55:08 +1200 (NZST)
Received: from berenddeboer.net [216.127.80.16]
	by localhost with POP3 (fetchmail-5.9.11)
	for berend@localhost (single-drop); Sun, 20 Apr 2003 16:55:08 +1200 (NZST)
Received: from rackshack.wellner.org (root@localhost)
	by berenddeboer.net (8.11.6/8.11.6) with ESMTP id h3K4rjT20428
	for <berend@berenddeboer.net>; Sun, 20 Apr 2003 04:53:45 GMT
X-ClientAddr: 64.119.218.75
Received: from puzzle.pobox.com (puzzle.pobox.com [64.119.218.75])
	by rackshack.wellner.org (8.11.6/8.11.6) with ESMTP id h3K4rjZ20423
	for <berend@berenddeboer.net>; Sun, 20 Apr 2003 04:53:45 GMT
Received: from puzzle.pobox.com (localhost [127.0.0.1])
	by puzzle.pobox.com (Postfix) with ESMTP id F1C2A75463
	for <berend@berenddeboer.net>; Sun, 20 Apr 2003 00:53:44 -0400 (EDT)
Delivered-To: berend@pobox.com
Received: from seznam.cz (unknown [203.200.178.124])
	by puzzle.pobox.com (Postfix) with SMTP
	id 83F9B755DD; Sun, 20 Apr 2003 00:53:28 -0400 (EDT)
Message-ID: <a56fb0e43689$b8eb703c$e41b4f03@ariasparks>
From: <ariasparks@seznam.cz>
To: <becky24@pobox.com>, <belfort@pobox.com>, <berend@pobox.com>,
	<bfernald@pobox.com>, <becky_divinski@pobox.com>
Subject: pc user
Date: Sat, 19 Apr 2003 21:10:26 -0600
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="----=_NextPart_E70_6B06_B2D10C8B.29ABC498"
X-Priority: 3
X-MimeOLE: Produced By Microsoft MimeOLE V5.00.2615.200
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 5.00.2615.200
X-Spam-Status: No, hits=4.1 required=5.0
	tests=BASE64_ENC_TEXT,LINES_OF_YELLING,NO_REAL_NAME,
	      SPAM_PHRASE_00_01,UPPERCASE_50_75,USER_AGENT_OE
	version=2.43
X-Spam-Level: ****

------=_NextPart_E70_6B06_B2D10C8B.29ABC498
Content-Type: text/plain;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable


------=_NextPart_E70_6B06_B2D10C8B.29ABC498
Content-Type: text/html;
	charset="iso-8859-1"
Content-Transfer-Encoding: base64


PCFET0NUWVBFIEhUTUwgUFVCTElDICItLy9XM0MvL0RURCBIVE1MIDQuMDEg
VHJhbnNpdGlvbmFsLy9FTiI+DQoNCjxodG1sPg0KPGhlYWQ+DQoJPHRpdGxl
Plplcm8gQWRzITwvdGl0bGU+DQo8L2hlYWQ+DQoNCjxib2R5PjxjZW50ZXI+
DQogIDx0YWJsZSB3aWR0aD0iNTAiIGJvcmRlcj0iMSIgY2VsbHNwYWNpbmc9
IjAiIGNlbGxwYWRkaW5nPSIwIj4NCiAgICA8dHI+DQogICAgICA8dGQ+DQog
ICAgICAgIDx0YWJsZSB3aWR0aD0iNTAiIGJvcmRlcj0iMCIgY2VsbHNwYWNp
bmc9IjAiIGNlbGxwYWRkaW5nPSIwIj4NCiAgICAgICAgICA8dHI+IA0KICAg
ICAgICAgICAgPHRkPjxhIGhyZWY9IiMiPjxpbWcgc3JjPSJodHRwOi8vMTI4
LjI0Mi4xMDAuODUvemVyb2FkL2ltYWdlcy9aQUxHMDgxNk4vemFsZzA4MTZu
MDMuZ2lmIiB3aWR0aD0iMzIwIiBoZWlnaHQ9IjQ2IiBib3JkZXI9MD48L2E+
PC90ZD4NCiAgICAgICAgICAgIDx0ZD48YSBocmVmPSIjIj48aW1nIHNyYz0i
aHR0cDovLzEyOC4yNDIuMTAwLjg1L3plcm9hZC9pbWFnZXMvWkFMRzA4MTZO
L3phbGcwODE2bjAyLmpwZyIgd2lkdGg9IjgwIiBoZWlnaHQ9IjQ2IiBib3Jk
ZXI9MD48L2E+PC90ZD4NCiAgICAgICAgICA8L3RyPg0KICAgICAgICAgIDx0
cj4gDQogICAgICAgICAgICA8dGQ+PGEgaHJlZj0iIyI+PGltZyBzcmM9Imh0
dHA6Ly8xMjguMjQyLjEwMC44NS96ZXJvYWQvaW1hZ2VzL1pBTEcwODE2Ti96
YWxnMDgxNm4wMS5naWYiIHdpZHRoPSIzMjAiIGhlaWdodD0iMzkiIGJvcmRl
cj0wPjwvYT48L3RkPg0KICAgICAgICAgICAgPHRkPjxhIGhyZWY9IiMiPjxp
bWcgc3JjPSJodHRwOi8vMTI4LjI0Mi4xMDAuODUvemVyb2FkL2ltYWdlcy9a
QUxHMDgxNk4vemFsZzA4MTZuMDQuanBnIiB3aWR0aD0iODAiIGhlaWdodD0i
MzkiIGJvcmRlcj0wPjwvYT48L3RkPg0KICAgICAgICAgIDwvdHI+DQogICAg
ICAgICAgPHRyPiANCiAgICAgICAgICAgIDx0ZCBjb2xzcGFuPSIyIj4gDQog
ICAgICAgICAgICAgIDx0YWJsZSB3aWR0aD0iNTAiIGJvcmRlcj0iMCIgY2Vs
bHNwYWNpbmc9IjAiIGNlbGxwYWRkaW5nPSIwIj4NCiAgICAgICAgICAgICAg
ICA8dHI+IA0KICAgICAgICAgICAgICAgICAgPHRkPjxhIGhyZWY9IiMiPjxp
bWcgc3JjPSJodHRwOi8vMTI4LjI0Mi4xMDAuODUvemVyb2FkL2ltYWdlcy9a
QUxHMDgxNk4vemFsZzA4MTZuMDUuZ2lmIiB3aWR0aD0iMjIwIiBoZWlnaHQ9
Ijc1IiBib3JkZXI9MD48L2E+PC90ZD4NCiAgICAgICAgICAgICAgICAgIDx0
ZD48YSBocmVmPSIjIj48aW1nIHNyYz0iaHR0cDovLzEyOC4yNDIuMTAwLjg1
L3plcm9hZC9pbWFnZXMvWkFMRzA4MTZOL3phbGcwODE2bjA2LmpwZyIgd2lk
dGg9IjE4MCIgaGVpZ2h0PSI3NSIgYm9yZGVyPTA+PC9hPjwvdGQ+DQogICAg
ICAgICAgICAgICAgPC90cj4NCiAgICAgICAgICAgICAgICA8dHI+IA0KICAg
ICAgICAgICAgICAgICAgPHRkIGNvbHNwYW49IjIiPiANCiAgICAgICAgICAg
ICAgICAgICAgPHRhYmxlIHdpZHRoPSI1MCIgYm9yZGVyPSIwIiBjZWxsc3Bh
Y2luZz0iMCIgY2VsbHBhZGRpbmc9IjAiPg0KICAgICAgICAgICAgICAgICAg
ICAgIDx0cj4gDQogICAgICAgICAgICAgICAgICAgICAgICA8dGQ+PGEgaHJl
Zj0iIyI+PGltZyBzcmM9Imh0dHA6Ly8xMjguMjQyLjEwMC44NS96ZXJvYWQv
aW1hZ2VzL1pBTEcwODE2Ti96YWxnMDgxNm4wNi5naWYiIHdpZHRoPSIyODgi
IGhlaWdodD0iMTAwIiBib3JkZXI9MD48L2E+PC90ZD4NCiAgICAgICAgICAg
ICAgICAgICAgICAgIDx0ZD48YSBocmVmPSIjIj48aW1nIHNyYz0iaHR0cDov
LzEyOC4yNDIuMTAwLjg1L3plcm9hZC9pbWFnZXMvWkFMRzA4MTZOL3phbGcw
ODE2bjA4LmpwZyIgd2lkdGg9IjExMiIgaGVpZ2h0PSIxMDAiIGJvcmRlcj0w
PjwvYT48L3RkPg0KICAgICAgICAgICAgICAgICAgICAgIDwvdHI+DQogICAg
ICAgICAgICAgICAgICAgICAgPHRyPiANCiAgICAgICAgICAgICAgICAgICAg
ICAgIDx0ZCBjb2xzcGFuPSIyIj4gDQogICAgICAgICAgICAgICAgICAgICAg
ICAgIDx0YWJsZSB3aWR0aD0iNTAiIGJvcmRlcj0iMCIgY2VsbHNwYWNpbmc9
IjAiIGNlbGxwYWRkaW5nPSIwIj4NCiAgICAgICAgICAgICAgICAgICAgICAg
ICAgICA8dHI+IA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHRk
PjxhIGhyZWY9Imh0dHA6Ly93d3cuemVyb2Fkcy5jb20vbGFuZGluZ3BhZ2Uv
P1JlZklkPTc3MjUwIj48aW1nIHNyYz0iaHR0cDovLzEyOC4yNDIuMTAwLjg1
L3plcm9hZC9pbWFnZXMvWkFMRzA4MTZOL3phbGcwODE2bjA5LmdpZiIgd2lk
dGg9IjI4OCIgaGVpZ2h0PSI2MCIgYm9yZGVyPTA+PC9hPjwvdGQ+DQogICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICA8dGQ+PGEgaHJlZj0iIyI+PGlt
ZyBzcmM9Imh0dHA6Ly8xMjguMjQyLjEwMC44NS96ZXJvYWQvaW1hZ2VzL1pB
TEcwODE2Ti96YWxnMDgxNm4xMC5naWYiIHdpZHRoPSIxMTIiIGhlaWdodD0i
NjAiIGJvcmRlcj0wPjwvYT48L3RkPg0KICAgICAgICAgICAgICAgICAgICAg
ICAgICAgIDwvdHI+DQogICAgICAgICAgICAgICAgICAgICAgICAgIDwvdGFi
bGU+DQogICAgICAgICAgICAgICAgICAgICAgICA8L3RkPg0KICAgICAgICAg
ICAgICAgICAgICAgIDwvdHI+DQogICAgICAgICAgICAgICAgICAgIDwvdGFi
bGU+DQogICAgICAgICAgICAgICAgICA8L3RkPg0KICAgICAgICAgICAgICAg
IDwvdHI+DQogICAgICAgICAgICAgIDwvdGFibGU+DQogICAgICAgICAgICA8
L3RkPg0KICAgICAgICAgIDwvdHI+DQogICAgICAgIDwvdGFibGU+DQogICAg
ICA8L3RkPg0KICAgIDwvdHI+DQogIDwvdGFibGU+DQo8L2NlbnRlcj4NCjxw
PiZuYnNwOzwvcD4NCjxwPiZuYnNwOzwvcD4NCjxwPiZuYnNwOzwvcD4NCjxw
PiZuYnNwOzwvcD4NCjxwPllvdSBoYXZlIHJlY2VpdmVkIHRoaXMgb2ZmZXIg
YmVjYXVzZSB0aGlzIGVtYWlsIGFkZHJlc3Mgd2FzIHN1Ym1pdHRlZCB0byBv
bmUNCm9mIG91ciBhZmZpbGlhdGUgc2l0ZXMuJm5ic3A7IFdlIGhvbm9yIGFs
bCByZW1vdmUgcmVxdWVzdHMgd2l0aGluIDcyIGhvdXJzLg0KUGxlYXNlIDxh
IGhyZWY9Imh0dHA6Ly8xOTMuMjMxLjI0OC42Ni9jYW1wMDIvcmVtb3Zlcy9v
ZmYuaHRtIj5jbGljayBoZXJlPC9hPiB0bw0KYmUgcmVtb3ZlZC48L3A+DQo8
L2JvZHk+DQoNCmhrZGRjeGFqYmtkZGN4d2xCSU9pDQo8L2h0bWw+

------=_NextPart_E70_6B06_B2D10C8B.29ABC498--



