Return-Path: <cyrus@bmach.nederware.nl>
Received: from bmach.nederware.nl ([unix socket])
	by bmach.nederware.nl (Cyrus v2.1.9) with LMTP; Wed, 11 Sep 2002 19:05:08 +1200
X-Sieve: CMU Sieve 2.2
Return-Path: <cetusbounce@cetus-links.org>
Received: from localhost (localhost.nederware.nl [127.0.0.1])
	by bmach.nederware.nl (Postfix) with ESMTP id 5941D22FDC
	for <berend@localhost>; Wed, 11 Sep 2002 19:05:08 +1200 (NZST)
Received: from pop3.xtra.co.nz [203.96.92.132]
	by localhost with POP3 (fetchmail-5.9.11)
	for berend@localhost (single-drop); Wed, 11 Sep 2002 19:05:08 +1200 (NZST)
Received: from mta2-rme.xtra.co.nz ([210.86.15.142])
          by mta201-rme.xtra.co.nz with ESMTP
          id <20020911070231.PPOF1173.mta201-rme.xtra.co.nz@mta2-rme.xtra.co.nz>
          for <berenddeboer@xtra.co.nz>; Wed, 11 Sep 2002 19:02:31 +1200
Received: from dolly1.pobox.com ([207.106.49.22]) by mta2-rme.xtra.co.nz
          with ESMTP
          id <20020911070230.LNMN19105.mta2-rme.xtra.co.nz@dolly1.pobox.com>
          for <berenddeboer@xtra.co.nz>; Wed, 11 Sep 2002 19:02:30 +1200
Received: from dolly1.pobox.com (localhost.localdomain [127.0.0.1])
	by dolly1.pobox.com (Postfix) with ESMTP id DD67B2BFE9
	for <berenddeboer@xtra.co.nz>; Wed, 11 Sep 2002 03:02:29 -0400 (EDT)
Delivered-To: berend@pobox.com
Received: from omega.ipcinc.net (omega.ipcinc.net [205.243.147.100])
	by dolly1.pobox.com (Postfix) with ESMTP id 42FB22C018
	for <berend@pobox.com>; Wed, 11 Sep 2002 03:02:28 -0400 (EDT)
Received: (from cetus@localhost)
	by omega.ipcinc.net (8.11.6/8.11.2) id g8B71uD22257;
	Wed, 11 Sep 2002 02:01:56 -0500
Resent-Date: Wed, 11 Sep 2002 02:01:53 -0500
Resent-Message-Id: <200209110701.g8B71uD22257@omega.ipcinc.net>
Received: from yahoo.co.kr ([61.75.67.135])
	by omega.ipcinc.net (8.11.6/8.11.2) with SMTP id g8B71ps22231
	for <cetusfeedback@cetus-links.org>; Wed, 11 Sep 2002 02:01:52 -0500
Message-Id: <200209110701.g8B71ps22231@omega.ipcinc.net>
Reply-To: tysajii@yahoo.co.kr
From: XXXXXXXX <tysajii@yahoo.co.kr>
To: <cetusfeedback@cetus-links.org>
Subject: (XXXX)XXXXXXXXXX XXXXXXXX...
Sender: XXXXXXXX <tysajii@yahoo.co.kr>
Mime-Version: 1.0
Content-Type: text/html; charset="ks_c_5601-1987"
Date: Wed, 11 Sep 2002 15:58:20 +0900
X-Loop: cetusfeedback@cetus-links.org
Resent-From: cetusfeedback@cetus-links.org

<html>
<head>
<title>카드가 연체 되거나신용불량이되면즉각카드회사는채권관리팀(주로전직형사출신들을고용하고있슴)에카드채권을넘겨서처음부터펄펄뛰기시작합니다.형사고소를하네마네하며협박은물론이고진짜형사고발하는경우가있습니다.하지만형사고발이될수는있지만감방에간다거나하는</title>
<meta name="generator" content="Namo WebEditor v4.0">
</head>
<body bgcolor="white" text="black" link="blue" vlink="purple" alink="red">
<P>
<b>카드가 <font color="red">연체</font> 되거나 <font color="red">신용불량</font>이되면 즉각 카드회사는 채권관리팀(주로 <font color="red">전직형사</font>출신들을 고용하고 있슴)에 카드채권을 넘겨서 처음부터 펄펄뛰기 시작합니다. <font color="red">
형사고소</font>를 하네 마네 하며 협박은 물론이고 진짜 형사고발하는 경우가 있습니다. 하지만 형사고발이 될수는 있지만 감방에 간다거나 하는 일은 많이 
 
없습니다.<BR>협박이 안통할 경우 가족은 물론 터무니없는 처가쪽 까지 전화번호를 어떻게 알아냈는지 대신 물어내라고 어이없는 억지를 부립니다. 
이렇게 창피를 줌으로인해 혹시나 돈을 받아낼수 있지않을까..에서요. 새벽에 집으로 
찾아오는경우도 있습니다.<BR>카드빚이 몰리면 고민이 이만저만이 아닙니다. 형편이란 언제 어디서 
풀릴지 모르므로 형편이 풀릴때까지 신용불량은 절대로 막아야 합니다.고로 신용불량이 걸릴 위기에 처해있을때는  되도록이면 신용불량에 걸리지 않도록 
조심조심.....(500만원불량이나 5000만원불량이나 불량은 마찬가지 입니다.) 신용불량을 
막기 위한  <a href="http://well.infomaster.co.kr"><font color="blue">각종카드에 
대한 정보</font></a>로 신용불량을 막으시기 바랍니다.</b></P>
<P><B>   <center><a href='http://itnsoft.com/~mailtouch/user/touch.cgi?cmd=refuse_view&usercode=iljmgnny-kommiq-Ggljm&group=24&name=&mail=cetusfeedback@cetus-links.org'><img src='http://itnsoft.com/~mailtouch/user/mail-refuse.gif' border=0)></center><BR><BR><BR><BR></B><BR><BR></P>
</body>
</html>




