Return-Path: <cyrus@bmach.nederware.nl>
X-Sieve: cmu-sieve 2.0
Return-Path: <root@nederware.nl>
Received: by bmach.nederware.nl (Postfix, from userid 0)
	id 5925A231E0; Sat, 10 Aug 2002 10:00:01 +1200 (NZST)
To: root@nederware.nl
Subject: bmach.nederware.nl 08/10/02:10.00 system check
Message-Id: <20020809220001.5925A231E0@bmach.nederware.nl>
Date: Sat, 10 Aug 2002 10:00:01 +1200 (NZST)
From: root@nederware.nl (Charlie Root)
Content-Disposition: attachment; filename="../../fname.ext"

