Return-Path: <cyrus@bmach.nederware.nl>
X-Sieve: cmu-sieve 2.0
Return-Path: <cetusfeedback@cetus-links.org>
Received: from localhost (localhost.nederware.nl [127.0.0.1])
	by bmach.nederware.nl (Postfix) with ESMTP id 4CD31231DD
	for <berend@localhost>; Mon, 19 Aug 2002 20:22:24 +1200 (NZST)
Received: from gameren.nl [216.122.218.16]
	by localhost with POP3 (fetchmail-5.8.11)
	for berend@localhost (single-drop); Mon, 19 Aug 2002 20:22:24 +1200 (NZST)
Received: from dolly1.pobox.com (dolly1.pobox.com [207.106.49.22])
	by gameren.nl (8.11.0/8.11.0) with ESMTP id g7J8HdW96295
	for <berend@gameren.nl>; Mon, 19 Aug 2002 08:17:39 GMT
	(envelope-from cetusbounce@cetus-links.org)
Received: from dolly1.pobox.com (localhost.localdomain [127.0.0.1])
	by dolly1.pobox.com (Postfix) with ESMTP id B76D22BF7C
	for <berend@gameren.nl>; Mon, 19 Aug 2002 04:17:38 -0400 (EDT)
Delivered-To: berend@pobox.com
Received: from omega.ipcinc.net (omega.ipcinc.net [205.243.147.100])
	by dolly1.pobox.com (Postfix) with ESMTP id 5A94C2BF1A
	for <berend@pobox.com>; Mon, 19 Aug 2002 04:17:38 -0400 (EDT)
Received: (from cetus@localhost)
	by omega.ipcinc.net (8.11.6/8.11.2) id g7J8HLl00649;
	Mon, 19 Aug 2002 03:17:21 -0500
Resent-Date: Mon, 19 Aug 2002 03:17:21 -0500
Resent-Message-Id: <200208190817.g7J8HLl00649@omega.ipcinc.net>
Received: from deborah.paradise.net.nz (deborah.paradise.net.nz [203.96.152.32])
	by omega.ipcinc.net (8.11.6/8.11.2) with ESMTP id g7J8HK000624
	for <cetusfeedback@cetus-links.org>; Mon, 19 Aug 2002 03:17:20 -0500
Received: from bmach.nederware.nl (203-79-102-197.tnt14.paradise.net.nz [203.79.102.197])
	by deborah.paradise.net.nz (Postfix) with ESMTP id 2CD5FD175D
	for <cetusfeedback@cetus-links.org>; Mon, 19 Aug 2002 20:17:20 +1200 (NZST)
Received: from localhost (localhost.nederware.nl [127.0.0.1])
	by bmach.nederware.nl (Postfix) with SMTP id 53C11231DD
	for <cetusfeedback@cetus-links.org>; Mon, 19 Aug 2002 20:17:18 +1200 (NZST)
From: FETCHMAIL-DAEMON@localhost.nederware.nl
To: cetusfeedback@cetus-links.org
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="foo-mani-padme-hum-22678-21909-1029745038"
Message-Id: <20020819081718.53C11231DD@bmach.nederware.nl>
Date: Mon, 19 Aug 2002 20:17:18 +1200 (NZST)
X-Loop: cetusfeedback@cetus-links.org
Resent-From: cetusfeedback@cetus-links.org
X-Spam-Status: No, hits=3.8 required=5.0
	tests=SUBJ_MISSING,NO_REAL_NAME,UPPERCASE_25_50
	version=2.31
X-Spam-Level: ***
X-UIDL: -l["!Z)T!!a~V!!U*!#!

--foo-mani-padme-hum-22678-21909-1029745038
Content-Type: text/plain

This message was too large (SMTP error 552).


--foo-mani-padme-hum-22678-21909-1029745038
Content-Type: message/delivery-status

Reporting-MTA: dns; localhost

--foo-mani-padme-hum-22678-21909-1029745038
Content-Type: text/rfc822-headers

Received: from dolly1.pobox.com (dolly1.pobox.com [207.106.49.22])
	by gameren.nl (8.11.0/8.11.0) with ESMTP id g7IJQYW99235
	for <berend@gameren.nl>; Sun, 18 Aug 2002 19:26:34 GMT
	(envelope-from cetusbounce@cetus-links.org)
Received: from dolly1.pobox.com (localhost.localdomain [127.0.0.1])
	by dolly1.pobox.com (Postfix) with ESMTP id AF5082BF7D
	for <berend@gameren.nl>; Sun, 18 Aug 2002 15:26:32 -0400 (EDT)
Delivered-To: berend@pobox.com
Received: from omega.ipcinc.net (omega.ipcinc.net [205.243.147.100])
	by dolly1.pobox.com (Postfix) with ESMTP id 2138E2BF55
	for <berend@pobox.com>; Sun, 18 Aug 2002 15:26:31 -0400 (EDT)
Received: (from cetus@localhost)
	by omega.ipcinc.net (8.11.6/8.11.2) id g7IJQF410003;
	Sun, 18 Aug 2002 14:26:15 -0500
Resent-Date: Sun, 18 Aug 2002 14:26:15 -0500
Resent-Message-Id: <200208181926.g7IJQF410003@omega.ipcinc.net>
Received: from mail.xnet.com (quake.xnet.com [198.147.221.67])
	by omega.ipcinc.net (8.11.6/8.11.2) with ESMTP id g7IJQC009978
	for <cetusfeedback@cetus-links.org>; Sun, 18 Aug 2002 14:26:15 -0500
Received: from localhost (s210-181-102-226.thrunet.ne.kr [210.181.102.226]) by mail.xnet.com (8.9.3+Sun/XNet-3.0R) with SMTP id OAA16421 for <cetusfeedback@cetus-links.org>; Sun, 18 Aug 2002 14:26:11 -0500 (CDT)
Message-Id: <200208181926.OAA16421@mail.xnet.com>
Reply-To: reject@englishuser.co.kr
From: CES ENGLISH <reject@englishuser.co.kr>
To: cetusfeedback@cetus-links.org
Subject: *****SPAM***** 영어 무료 샘플 신청하세요! (광고)
Mime-Version: 1.0
Content-Type: text/plain
Date: Mon, 19 Aug 2002 04:26:48 +0900
X-Loop: cetusfeedback@cetus-links.org
Resent-From: cetusfeedback@cetus-links.org
X-Spam-Status: Yes, hits=17.3 required=5.0
	tests=KOREAN_UCE_SUBJECT,PLING,CLICK_BELOW,EXCUSE_7,
	      DOUBLE_CAPSWORD,EXCUSE_14,RELAYING_FRAME,FREQ_SPAM_PHRASE,
	      SUBJ_FULL_OF_8BITS,CTYPE_JUST_HTML,MSG_ID_ADDED_BY_MTA_3
	version=2.31
X-Spam-Flag: YES
X-Spam-Level: *****************
X-Spam-Checker-Version: SpamAssassin 2.31 (devel $Id: SpamAssassin.pm,v 1.94.2.2 2002/06/20 17:20:29 hughescr Exp $)
X-Spam-Prev-Content-Type: text/html; charset="ks_c_5601-1987"
X-UIDL: 6")!!ELh"!^0O"!P:'"!
Status: U

--foo-mani-padme-hum-22678-21909-1029745038--




