Return-Path: <cyrus@bmach.nederware.nl>
Received: from bmach.nederware.nl ([unix socket])
	by bmach.nederware.nl (Cyrus v2.1.9) with LMTP; Sun, 20 Apr 2003 05:45:07 +1200
X-Sieve: CMU Sieve 2.2
Return-Path: <choami100@freechal.com>
Received: from localhost (localhost.nederware.nl [127.0.0.1])
	by bmach.nederware.nl (Postfix) with ESMTP id 1EA5F22FDC
	for <berend@localhost>; Sun, 20 Apr 2003 05:45:07 +1200 (NZST)
Received: from berenddeboer.net [216.127.80.16]
	by localhost with POP3 (fetchmail-5.9.11)
	for berend@localhost (single-drop); Sun, 20 Apr 2003 05:45:07 +1200 (NZST)
Received: from rackshack.wellner.org (root@localhost)
	by berenddeboer.net (8.11.6/8.11.6) with ESMTP id h3JHfOF10391
	for <berend@berenddeboer.net>; Sat, 19 Apr 2003 17:41:24 GMT
X-ClientAddr: 64.119.218.75
Received: from puzzle.pobox.com (puzzle.pobox.com [64.119.218.75])
	by rackshack.wellner.org (8.11.6/8.11.6) with ESMTP id h3JHfOZ10386
	for <berend@berenddeboer.net>; Sat, 19 Apr 2003 17:41:24 GMT
Received: from puzzle.pobox.com (localhost [127.0.0.1])
	by puzzle.pobox.com (Postfix) with ESMTP id 517BD75501
	for <berend@berenddeboer.net>; Sat, 19 Apr 2003 13:41:24 -0400 (EDT)
Delivered-To: berend@pobox.com
Received: from alias.acm.org (alias.acm.org [199.222.69.90])
	by puzzle.pobox.com (Postfix) with ESMTP id 9D59A75742
	for <berend@pobox.com>; Sat, 19 Apr 2003 13:41:23 -0400 (EDT)
Received: from test.com ([211.177.255.172])
        by alias.acm.org (ACM Email Forwarding Service) with SMTP id COB73880
        for <berend@acm.org>; Sat, 19 Apr 2003 13:41:21 -0400
From: XXXXXX <choami100@freechal.com>
To: 
Subject: =?ks_c_5601-1987?q?(=B1=A4=B0=ED)=B9=D9=C5=C1=C8=AD=B8=E9=BF=A1_=B3=BB=C8=A8=C6=E4=C0=CC=C1=F6_=BE=C6=C0=CC=C4=DC=C0=CC_=C0=DA=B5=BF=C0=B8=B7=CE_=BB=FD=BC=BA=B5=C8=B4=D9=B8=E9..?=
Date: Sun, 20 Apr 2003 02:41:19 +0900
X-Mailer: EVAMAIL 1.2
MIME-Version: 1.0
Content-Type: multipart/related; boundary="edbfdc5d-c4a5-4c2a-bebc-0e0329cee6fc"
Content-Transfer-Encoding: quoted-printable
Reply-To: XXXXXX <choami100@freechal.com>
Message-Id: <20030419174123.9D59A75742@puzzle.pobox.com>
X-Spam-Status: Yes, hits=10.3 required=5.0
	tests=BIG_FONT,FROM_ENDS_IN_NUMS,HEADER_8BITS,
	      HTML_FONT_COLOR_BLUE,HTML_FONT_COLOR_NAME,
	      HTML_FONT_COLOR_RED,MIME_EXCESSIVE_QP,MIME_LONG_LINE_QP,
	      MISSING_HEADERS,RATWARE_EVAMAIL,SPAM_PHRASE_00_01,TO_EMPTY
	version=2.43
X-Spam-Flag: YES
X-Spam-Level: **********
X-Spam-Checker-Version: SpamAssassin 2.43 (1.115.2.20-2002-10-15-exp)
X-Spam-Report:   10.30 hits, 5 required;
  *  2.6 -- Bulk email software fingerprint (EVAMAIL) found in headers
  *  2.4 -- Headers include 3 consecutive 8-bit characters
  *  0.9 -- From: ends in numbers
  *  0.2 -- To: is empty
  *  0.8 -- BODY: Spam phrases score is 00 to 01 (low)
  *  0.3 -- BODY: FONT Size +2 and up or 3 and up
  *  0.3 -- BODY: HTML font color has unusual name
  *  0.3 -- BODY: HTML font color is red
  *  0.2 -- BODY: HTML font color is blue
  *  1.0 -- RAW: Excessive quoted-printable encoding in body
  *  0.3 -- RAW: Quoted-printable line longer than 76 characters
  *  1.0 -- Missing To: header

This is a multi-part message in MIME format
--edbfdc5d-c4a5-4c2a-bebc-0e0329cee6fc
Content-Type: text/html; charset=ks_c_5601-1987
Content-Transfer-Encoding: quoted-printable


<HR><p align=3D"left"><font size=3D"2">O =C0=CC=B8=DE=C0=CF =C3=DF=C3=E2 URL =
: </font><BR></a><font size=3D3><b>=B9=D9=C5=C1=C8=AD=B8=E9 =BE=C6=C0=CC=C4=DC=
 =C0=DA=B5=BF=BB=FD=BC=BA=B1=E2(=B9=D9=C4=DC BaCon)</b></font><br><br>
<font size=3D2><a href=3D"http://hidream.or.kr/mailman/bacon.html" target=3D=
"_blank"><b>=C7=C1=B7=CE=B1=D7=B7=A5 =BC=B3=B8=ED</b></a>&nbsp; 

<a href=3D"http://hidream.or.kr/mailman/bacon.html" target=3D"_blank"><b>=B5=
=A5=B8=F0=C6=E4=C0=CC=C1=F6 =BA=B8=B1=E2</b></a>&nbsp; 

<a href=3D"http://hidream.or.kr/mailman/bacon.html" target=3D"_blank"><b>=C1=
=A6=C0=DB=C0=C7=B7=DA =BD=C5=C3=BB=C7=CF=B1=E2</b></a>&nbsp; 

<a href=3D"http://hidream.or.kr/mailman/bacon.html" target=3D"_blank"><b>=C7=
=C1=B7=CE=B1=D7=B7=A5 =BC=B3=C4=A1=B9=E6=B9=FD</b></a></font><br><br> 

<font size=3D2 color=3Dblue><b>=B9=D9=C4=DC(BaCon)=C0=BA =B3=D7=C6=BC=C1=F0=C0=
=CC =B3=BB=C8=A8=C6=E4=C0=CC=C1=F6=BF=A1 =B9=E6=B9=AE=C7=CF=B4=C2 =BC=F8=B0=A3=
, =B9=E6=B9=AE=C0=DA=C0=C7 =C4=C4=C7=BB=C5=CD =B9=D9=C5=C1=C8=AD=B8=E9=BF=A1=
<br>
=B3=BB=C8=A8=C6=E4=C0=CC=C1=F6=C0=C7 =BF=AC=B0=E1 =BE=C6=C0=CC=C4=DC=C0=CC =C0=
=DA=B5=BF=C0=B8=B7=CE =BB=FD=BC=BA=B5=C7=B5=B5=B7=CF =C7=CF=B4=C2 =C7=C1=B7=CE=
=B1=D7=B7=A5=C0=D4=B4=CF=B4=D9.</b></font><br>

<font size=3D2 color=3Dred><b>=C0=CC=C1=A6=B4=C2 =BD=C5=B1=D4 =B9=E6=B9=AE=C0=
=DA=B8=A6 =BB=F5=B7=D3=B0=D4 =C3=A2=C3=E2=C7=CF=B4=C2 =B0=CD=B5=B5 =C1=DF=BF=
=E4=C7=CF=C1=F6=B8=B8,<br>

=C7=D1=B9=F8 =B3=BB=C8=A8=C6=E4=C0=CC=C1=F6=B8=A6 =B9=E6=B9=AE=C7=DF=B4=F8 =B3=
=D7=C6=BC=C1=F0=B5=E9=C0=BB =B4=D9=BD=C3 =C0=E7 =B9=E6=B9=AE=C4=C9 =C7=CF=B4=
=C2 =B0=CD=C0=CC =B4=F5=BF=ED =C1=DF=BF=E4=C7=D5=B4=CF=B4=D9=
</b></font><br><br>
<font size=3D2><b>=B9=D9=C4=DC =BC=B3=C4=A1=BF=B9 :</b> =BE=C6=B7=A1=C0=C7 =BE=
=C6=C0=CC=C4=DC=C0=BB =C5=AC=B8=AF=C7=CF=B8=E9 =B3=BB =C4=C4=C7=BB=C5=CD=C0=C7=
 =B9=D9=C5=C1=C8=AD=B8=E9=BF=A1 =C7=D8=B4=E7 =C8=A8=C6=E4=C0=CC=C1=F6=C0=C7 =
=BE=C6=C0=CC=C4=DC=C0=CC<br>
=C0=DA=B5=BF=C0=B8=B7=CE =BB=FD=BC=BA=B5=C7=B4=C2 =B0=CD=C0=BB =C8=AE=C0=CE=C7=
=D2 =BC=F6 =C0=D6=BD=C0=B4=CF=B4=D9.<br>
<a href=3D"http://www.yjland.com" target=3D"_blank"><img src=3D=
"http://hidream.or.kr/mailman/img2/yjland.gif" border=3D0 alt=3D"=BF=B5=C1=F8 =
=C4=C1=BC=B3=C6=C3"></a>=BF=B5=C1=F8 =C4=C1=BC=B3=C6=C3&nbsp;   
<a href=3D"http://www.goodcarmoa.com" target=3D"_blank"><img src=3D=
"http://hidream.or.kr/mailman/img2/goodcar.gif" border=3D0 alt=3D"=C1=DF=B0=ED=
=C2=F7=B8=C5=B8=C5"></a>=C1=DF=B0=ED=C2=F7=B8=C5=B8=C5&nbsp;
<a href=3D"http://www.rooibos.co.kr" target=3D"_blank"><img src=3D=
"http://hidream.or.kr/mailman/img2/rooibos.gif" border=3D0 alt=3D"=B7=E7=C0=CC=
=BA=B8=BD=BA"></a>=B7=E7=C0=CC=BA=B8=BD=BA&nbsp;
<a href=3D"http://www.daechulok.net" target=3D"_blank"><img src=3D=
"http://hidream.or.kr/mailman/img2/daechulok.gif" border=3D0 alt=3D"=C0=DA=B1=
=DD =C0=CF=B9=F8=C1=F6"></a>=C0=DA=B1=DD =C0=CF=B9=F8=C1=F6&nbsp; 
<a href=3D"http://www.bestopen.net" target=3D"_blank"><img src=3D=
"http://hidream.or.kr/mailman/img2/bestopen.gif" border=3D0 alt=3D"=BA=A3=BD=
=BA=C6=AE=BF=C0=C7=C2"></a>=BA=A3=BD=BA=C6=AE=BF=C0=C7=C2</font><br><br>     
=


<font size=3D2>1. =B0=B3=BF=E4<br>

  &nbsp;&nbsp;&nbsp;&nbsp;=C1=A4=C5=EB=BA=CE=B3=AA =C6=F7=C5=BB=BD=CE=C0=CC=C6=
=AE=B5=EE=C0=C7 =B0=A2=C1=BE =C0=CC=B8=DE=C0=CF,=B0=D4=BD=C3=C6=C7 =C8=AB=BA=
=B8=B9=E6=B9=FD=BF=A1 =B4=EB=C7=D1 =B9=FD=B7=FC=C0=FB,<br>

  &nbsp;&nbsp;&nbsp;&nbsp;=B1=E2=BC=FA=C0=FB =C1=A6=C1=A6=B7=CE =C1=DF=BC=D2=
=C7=FC =BD=CE=C0=CC=C6=AE=BF=EE=BF=B5=C0=DA=B5=E9=C0=BA =B8=B6=C4=C9=C6=C3=C0=
=BB =C7=CF=B4=C2=B5=A5,<br>

  &nbsp;&nbsp;&nbsp;&nbsp;=B8=B9=C0=BA =BE=EE=B7=C1=BF=F2=BF=A1 =BA=C0=C2=F8=
=C7=D8 =C0=D6=BD=C0=B4=CF=B4=D9.<br><br>



  &nbsp;&nbsp;&nbsp;&nbsp;=B5=FB=B6=F3=BC=AD, =BF=E4=C1=F2=B0=B0=C0=BA =C7=F6=
=BD=C7=BF=A1=BC=AD=B4=C2 =BD=C5=B1=D4 =B9=E6=B9=AE=C0=DA=B8=A6 =BB=F5=B7=D3=B0=
=D4 =C3=A2=C3=E2=C7=CF=B4=C2 =B0=CD=B5=B5 =C1=DF=BF=E4=C7=CF=C1=F6=B8=B8,<br>
=


  &nbsp;&nbsp;&nbsp;&nbsp;=B3=BB=C8=A8=C6=E4=C0=CC=C1=F6=B8=A6 =B9=E6=B9=AE=C7=
=DF=B4=F8 =B3=D7=C6=BC=C1=F0=B5=E9=C0=CC =B4=D9=BD=C3 =C0=E7 =B9=E6=B9=AE=C4=
=C9 =C7=CF=B4=C2 =B0=CD=C0=CC =B4=F5=BF=ED =C1=DF=BF=E4=C7=D5=B4=CF=B4=D9=
<br>

  &nbsp;&nbsp;&nbsp;&nbsp;=B8=B9=C0=BA =B9=E6=B9=FD=B5=E9=C0=CC =C0=D6=C1=F6=
=B8=B8 =BA=F1=BF=EB=B0=FA =BA=F1=B7=CA=C7=CF=B4=C2 =BC=BA=B0=FA=B8=A6 =B3=BB=
=B1=E2=B4=C2 =B9=AB=C3=B4=C0=CC=B3=AA =C8=FB=C0=CC =B5=EC=B4=CF=B4=D9=
<br><br>



  &nbsp;&nbsp;&nbsp;&nbsp;=C0=CC=B7=AF=C7=D1 =BB=F3=C8=B2=BF=A1=BC=AD =B9=D9=
=C5=C1=C8=AD=B8=E9 =BE=C6=C0=CC=C4=DC  =C0=DA=B5=BF =BB=FD=BC=BA=B1=E2(=C0=CF=
=B8=ED BaCon)=B8=A6 =C1=A6=BE=C8=C7=D5=B4=CF=B4=D9.<br><br> 

2. =B9=D9=C5=C1=C8=AD=B8=E9 =BE=C6=C0=CC=C4=DC =C0=DA=B5=BF=BB=FD=BC=BA=B1=E2=
=B6=F5?<br>
  &nbsp;&nbsp;&nbsp;&nbsp;=B9=D9=C5=C1=C8=AD=B8=E9 =BE=C6=C0=CC=C4=DC =C0=DA=
=B5=BF=BB=FD=BC=BA=B1=E2(=C0=CF=B8=ED BaCon)=B4=C2 =BD=B1=B0=ED =B4=DC=BC=F8=
=C7=D5=B4=CF=B4=D9.<br>
  &nbsp;&nbsp;1) =C0=CC=B8=DE=C0=CF =B8=B6=C4=C9=C6=C3=B5=EE=C0=B8=B7=CE =BE=
=D6=BD=E1 =B9=E6=B9=AE=C7=D1 =B9=E6=B9=AE=C0=DA=B8=A6 =B3=F5=C4=A5=BC=F6=B4=C2=
 =BE=F8=BD=C0=B4=CF=B4=D9.<br>
  &nbsp;&nbsp;2) =B9=E6=B9=AE=C0=DA=B0=A1 =BF=EC=BF=A9=B0=EE=C0=FD=B3=A1=BF=A1=
 =BF=EC=BF=AC=C8=F7 BaCon=C0=CC =BC=B3=C4=A1=B5=C8 =C8=A8=C6=E4=C0=CC=C1=F6=BF=
=A1 =B9=E6=B9=AE=C0=BB =C7=D5=B4=CF=B4=D9.<br>
  &nbsp;&nbsp;3) =B9=E6=B9=AE=C7=CF=B4=C2 =BC=F8=B0=A3 =B9=E6=B9=AE=C0=DA=C0=
=C7 =C4=C4=C7=BB=C5=CD =B9=D9=C5=C1=C8=AD=B8=E9=BF=A1 =B3=BB=C8=A8=C6=E4=C0=CC=
=C1=F6=C0=C7 =BE=C6=C0=CC=C4=DC=C0=CC =C0=DA=B5=BF=C0=B8=B7=CE =BB=FD=BC=BA=B5=
=CB=B4=CF=B4=D9.<br>
  &nbsp;&nbsp;4) =C0=CC =C8=C4 =B9=E6=B9=AE=C0=DA=B4=C2 =B9=D9=C5=C1=C8=AD=B8=
=E9=BF=A1 =BB=FD=BC=BA=B5=C8 =BE=C6=C0=CC=C4=DC=C0=BB =C5=AC=B8=AF=C7=CF=BF=A9=
 =C7=D8=B4=E7 =C8=A8=C6=E4=C0=CC=C1=F6=B8=A6 =B9=E6=B9=AE=C7=D5=B4=CF=B4=D9=
</font><br><br>

<font size=3D2 color=3Dblue><b>=B9=D9=C4=DC(BaCon)=C0=BA =B3=D7=C6=BC=C1=F0=C0=
=CC =B3=BB=C8=A8=C6=E4=C0=CC=C1=F6=BF=A1 =B9=E6=B9=AE=C7=CF=B4=C2 =BC=F8=B0=A3=
, =B9=E6=B9=AE=C0=DA=C0=C7 =C4=C4=C7=BB=C5=CD =B9=D9=C5=C1=C8=AD=B8=E9=BF=A1=
<br>
=B3=BB=C8=A8=C6=E4=C0=CC=C1=F6=C0=C7 =BF=AC=B0=E1 =BE=C6=C0=CC=C4=DC=C0=CC =C0=
=DA=B5=BF=C0=B8=B7=CE =BB=FD=BC=BA=B5=C7=B5=B5=B7=CF =C7=CF=B4=C2 =C7=C1=B7=CE=
=B1=D7=B7=A5=C0=D4=B4=CF=B4=D9.</b></font><br><br>
<table width=3D"550" border=3D0 cellpadding=3D0 cellspacing=3D0>

 <tr><td><font size=3D2>

<form action=3D"http://www.geobu.com/jsp/deny.jsp" method=3Dpost>

<input type=3Dhidden name=3Did value=3Dhidream>

<input type=3Dhidden name=3Dsender value=3Dhibognara@hanmir.com>

<input type=3Dhidden name=3Dsubject value=3D=B9=D9=C4=DC>

<p align=3Dcenter>=BC=F6=BD=C5=B0=C5=BA=CE=C7=D2 =C1=D6=BC=D2=B8=A6 =C0=D4=B7=
=C2=C8=C4=BF=A1 =BC=F6=BD=C5=B0=C5=BA=CE=B8=A6 =C5=AC=B8=AF=C7=D8 =C1=D6=BD=C3=
=B8=E9 =B8=DE=C0=CF=B9=DF=BC=DB=C0=CC =B5=C7=C1=F6 =BE=CA=BD=C0=B4=CF=B4=D9=
<br>

DENY E_MAIL <input name=3D"email">

<input type=3Dsubmit value=3D=BC=F6=BD=C5=B0=C5=BA=CE name=3D=
B1></form></font></td></tr></table>
--edbfdc5d-c4a5-4c2a-bebc-0e0329cee6fc--


