Return-Path: <cyrus@bmach.nederware.nl>
X-Sieve: cmu-sieve 2.0
Return-Path: <return@intercowel.co.kr>
Received: from localhost (localhost.nederware.nl [127.0.0.1])
	by bmach.nederware.nl (Postfix) with ESMTP id D08F123193
	for <berend@localhost>; Sat, 10 Aug 2002 10:00:38 +1200 (NZST)
Received: from gameren.nl [216.122.218.16]
	by localhost with POP3 (fetchmail-5.8.11)
	for berend@localhost (single-drop); Sat, 10 Aug 2002 10:00:38 +1200 (NZST)
Received: from cali-1.pobox.com (cali-1.pobox.com [64.71.166.114])
	by gameren.nl (8.11.0/8.11.0) with ESMTP id g79LxpW44309
	for <berend@gameren.nl>; Fri, 9 Aug 2002 21:59:52 GMT
	(envelope-from return@intercowel.co.kr)
Received: from cali-1.pobox.com (localhost.localdomain [127.0.0.1])
	by cali-1.pobox.com (Postfix) with ESMTP id EEAAD3E778
	for <berend@gameren.nl>; Fri,  9 Aug 2002 17:59:47 -0400 (EDT)
Delivered-To: berend@pobox.com
Received: from alias.acm.org (alias.acm.org [199.222.69.90])
	by cali-1.pobox.com (Postfix) with ESMTP id D6FD83E77D
	for <berend@pobox.com>; Fri,  9 Aug 2002 17:59:43 -0400 (EDT)
Received: from localhost ([211.59.151.153])
        by alias.acm.org (ACM Email Forwarding Service) with SMTP id COB73880
        for <berend@acm.org>; Fri, 09 Aug 2002 18:00:39 -0400
Reply-To: return@intercowel.co.kr
From: (XX) XXXXXXXX <return@intercowel.co.kr>
To: berend@acm.org
Subject: *****SPAM***** (XXXX)XXXXe-Business Web SiteXXXX XX Renewal XXXX(XXXX)
Mime-Version: 1.0
Content-Type: text/plain
Date: Sat, 10 Aug 2002 07:06:43 +0900
Message-Id: <20020809215943.D6FD83E77D@cali-1.pobox.com>
X-Spam-Status: Yes, hits=8.9 required=7.0
	tests=KOREAN_UCE_SUBJECT,DOUBLE_CAPSWORD,MAILTO_WITH_SUBJ,
	      MAILTO_LINK,CTYPE_JUST_HTML
	version=2.31
X-Spam-Flag: YES
X-Spam-Level: ********
X-Spam-Checker-Version: SpamAssassin 2.31 (devel $Id: SpamAssassin.pm,v 1.94.2.2 2002/06/20 17:20:29 hughescr Exp $)
X-Spam-Prev-Content-Type: text/html; charset="ks_c_5601-1987"
X-UIDL: pC,"!"el!!>`""!EAo"!

SPAM: -------------------- Start SpamAssassin results ----------------------
SPAM: This mail is probably spam.  The original message has been altered
SPAM: so you can recognise or block similar unwanted mail in future.
SPAM: See http://spamassassin.org/tag/ for more details.
SPAM: 
SPAM: Content analysis details:   (8.9 hits, 7 required)
SPAM: KOREAN_UCE_SUBJECT (3.4 points)  Subject: contains Korean unsolicited email tag
SPAM: DOUBLE_CAPSWORD    (1.1 points)  BODY: A word in all caps repeated on the line
SPAM: MAILTO_WITH_SUBJ   (1.9 points)  URI: Includes a link to send a mail with a subject
SPAM: MAILTO_LINK        (0.8 points)  BODY: Includes a URL link to send an email
SPAM: CTYPE_JUST_HTML    (1.7 points)  HTML-only mail, with no text version
SPAM: 
SPAM: -------------------- End of SpamAssassin results ---------------------

<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=euc-kr">
<title>홈페이지(Web Site)의 제작</title>
<meta name="generator" content="Namo WebEditor v5.0">
</head>
<body bgcolor="white" text="black" link="blue" vlink="purple" alink="red" leftmargin="0" marginwidth="0" topmargin="0" marginheight="0">
<table align="center" border="0" cellpadding="0" cellspacing="0" width="622" height="100%">
<tr>
<td width="622" valign="top">
<table border="0" cellpadding="0" cellspacing="0" width="622" background="http://www.cowel.com/~inter/mail/image/bg.gif">
<tr>
<td width="612">
<p><a href="http://www.intercowel.co.kr" target="_blank"><img src="http://www.cowel.com/~inter/mail/image/top-01.gif" width="622" height="42" border="0"></a></p>
</td>
</tr>
<tr>
<td width="612">
<p><img src="http://www.cowel.com/~inter/mail/image/main_img.jpg" width="622" height="211" border="0"></p>
</td>
</tr>
<tr>
<td width="612">
<table border="0" cellpadding="0" cellspacing="0" width="100%">
<tr>
<td width="612">
<table border="0" cellpadding="0" cellspacing="0" width="622">
<tr>
<td width="432" valign="top">
<table border="0" cellpadding="0" cellspacing="0" width="432">
<tr>
<td width="432" align="center">
<table border="0" cellpadding="0" cellspacing="0" width="409">
<tr>
<td width="422" height="42" valign="bottom">
<p><span style="font-size:9pt;"><a href="http://www.intercowel.co.kr/homepage/home_main.htm" target="_blank"><font color="#006600"><img src="http://www.cowel.com/~inter/mail/image/home.gif" width="409" height="29" border="0"></font></a></span></p>
</td>
</tr>
<tr>
<td width="422"><span style="font-size:9pt;"><font color="#006600"><br>
&nbsp;홈페이지(Web Site)의 제작은 작업 특성에 따라 수십명 이상의 아이디어가 &nbsp;결집되어 제작 되어야만 하는 시간과 아이디어의 결정판 입니다. <br>
&nbsp;(주)인터코웰은 고객들의 욕구에 맞추어  제작 Flow을 준비하고 있습
&nbsp;니다. &nbsp;<br>
&nbsp;리뉴얼
제작
: 급히
만든
기업홈페이지를
새롭게
꾸며드립니다.</font></span></td>
</tr>
<tr>
<td width="422">
<p><span style="font-size:9pt;"><font color="#006600"><br></font><a href="http://www.intercowel.co.kr/webhosting/web_main.htm" target="_blank"><font color="#006600"><img src="http://www.cowel.com/~inter/mail/image/web.gif" width="409" height="29" border="0"></font></a></span></p>
</td>
</tr>
<tr>
<td width="422">
<P><FONT color="#006600"><span style="font-size:9pt;"><br> &nbsp;웹호스팅이 필요한 대상 </span></FONT></P>
<P><span style="font-size:9pt;"><font color="#006600">&nbsp;인터넷으로 영리를 목적으로하든 비영리든 대형 Project의 사업이 아닌 모든 사람(기업)</font></span></P>
<P><span style="font-size:9pt;"><font color="#006600">&nbsp;중소 기업 및 소기업 Web Server 구축의 초기 투자 비용이 부담 스러운 <br>
&nbsp;중소기업 및 소기업 사업은 Step by
Step입니다.<BR> &nbsp;초기의 활용성에 비하여 저렴한 관리비용으로 얼마든지 사업에 필요한 부분
&nbsp;을 사용하실수가 있습니다.</font></span></P></td>
</tr>
<tr>
<td width="422">
<p><span style="font-size:9pt;"><font color="#006600"><br></font><a href="http://www.intercowel.co.kr/serverhosting/server_main.htm" target="_blank"><font color="#006600"><img src="http://www.cowel.com/~inter/mail/image/server.gif" width="409" height="29" border="0"></font></a></span></p>
</td>
</tr>
<tr>
<td width="422"><span style="font-size:9pt;"><font color="#006600"><br>
&nbsp;경제적인 리눅스 전용서버 또는 NT서버를 저렴한 가격으로 운영할 수 <br>
&nbsp;있습니다. <BR> &nbsp;다양한 컨텐츠 사업을 할수가 있고, 단일 목적의
웹호스팅 사업뿐아니라 <br> &nbsp;인터넷몰을 설치하여 <BR> &nbsp;EC호스팅등 다양한 사업을 무리없이 소자본으로 운영할 수 있습니다. <BR>&nbsp;</font></span></td>
</tr>
</table>
</td>
</tr>
</table>
</td>
<td width="190" valign="top">
<table border="0" cellpadding="0" cellspacing="0" width="190">
<tr>
<td width="190">
<p><img src="http://www.cowel.com/~inter/mail/image/100m.gif" width="190" height="202" border="0"></p>
</td>
</tr>
</table>
<p><img src="http://www.cowel.com/~inter/mail/image/22.gif" width="190" height="220" border="0"></p>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td width="612">
<table border="0" cellpadding="0" cellspacing="0" width="622">
<tr>
<td width="612" height="58">
<p><img src="http://www.cowel.com/~inter/mail/image/bar.gif" width="622" height="49" border="0"></p>
</td>
</tr>
<tr>
<td width="612">
<table border="0" cellpadding="0" cellspacing="0">
<tr>
<td width="200">
<p><a href="http://www.intercowel.co.kr/homepage/homeapply_main.htm" target="_blank"><img src="http://www.cowel.com/~inter/mail/image/home_li.gif" width="208" height="50" border="0"></a></p>
</td>
<td width="200">
<p><a href="http://www.intercowel.co.kr/webhosting/webapply_main.htm" target="_blank"><img src="http://www.cowel.com/~inter/mail/image/web_li.gif" width="209" height="50" border="0"></a></p>
</td>
<td width="200">
<p><a href="http://www.intercowel.co.kr/serverhosting/serverapply_main.htm" target="_blank"><img src="http://www.cowel.com/~inter/mail/image/server_li.gif" width="205" height="50" border="0"></a></p>
</td>
</tr>
</table>
<DIV align=center><FONT face=돋움 size=2><SPAN class=body><br>본 메일은 정보통신부 권고 사항에 의거하여
제목에 <B>[광고]</B></SPAN></FONT><SPAN class=body><FONT color=#666666 face=돋움><FONT
size=2><FONT color=#000000>라 표시된 광고 메일입니다.</FONT><BR></FONT><FONT face=돋움
size=2><SPAN class=body><FONT color=#000000>귀하의 메일주소는 웹 서핑중 알게된 것이며, E-Mail 주소
외에 다른 정보는 갖고 있지 않습니다.</FONT></SPAN></FONT><FONT color=#000000 size=2>
</FONT><FONT
size=2><BR><FONT color=#000000>더 이상 메일을 수신하고 싶지 않으시면
</FONT></FONT></FONT><A
href="mailto:return@intercowel.co.kr?subject=수신을거부합니다.&amp;body=메일을 더이상 수신하기를 원치 않습니다!"><FONT face=돋움><FONT
color=#000000><FONT size=2><FONT color=#0000ff>[수신
거부]</FONT></FONT></FONT></FONT></A><FONT face=돋움><FONT size=2>를 클릭해 주십시오.<BR>수신거부를 하시면 차후로 다시는 메일을
발송하지 않을 것입니다.<BR>&nbsp;</FONT></FONT></SPAN></DIV></td>
</tr>
</table>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td width="612">
<p><img src="http://www.cowel.com/~inter/mail/image/add.gif" width="622" height="36" border="0"></p>
</td>
</tr>
</table>
</td>
</tr>
</table>
</body>
</html>



